name = "mlir-unschool"
version = "0.1.0"
defaultTargets = ["mlir-unschool"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4-nightly-testing"
rev = "nightly-testing-2025-08-11"
