name = "circomvent"
version = "0.1.0"
defaultTargets = ["zk"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.22.0-rc2"

[[require]]
name = "CompPoly"
git = "https://github.com/NethermindEth/CompPoly.git"
rev = "master"

[[lean_lib]]
name = "zk"

